[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200
via_ir = true

[scripts]
extra_args = [
    "--via-ir"
]
